ALTER TABLE realtime_runtime_config 
ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT 'Default Transport',
ADD COLUMN IF NOT EXISTS provider_type TEXT NOT NULL DEFAULT 'livekit',
ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
